branch-defaults:
  docker:
    environment: null
    group_suffix: null
  master:
    environment: dev-env
    group_suffix: null
environment-defaults:
  dev-env:
    branch: null
    repository: null
global:
  application_name: datathon-tutorial
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
